/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xdadapdfhaisstzkjhkp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkYWRhcGRmaGFpc3N0emtqaGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyNjMzMjksImV4cCI6MjEwMjgzOTMyOX0.75NRht0PFogy6mEA-jMTijI7PO6jQtLRHaRl8I7--OA"